name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select Environment to run tests against'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          # You can add 'qa' or 'test' here later once you create those environments

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          VALID_USERNAME: ${{ secrets.PROD_USERNAME }}
          VALID_PASSWORD: ${{ secrets.PROD_PASSWORD }}
        run: npx playwright test src/tests
